FROM arm64v8/ubuntu:20.04
WORKDIR /app

COPY ./libs/start.sh ./start.sh

RUN apt-get update
RUN apt-get install -y apt-utils
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install opensc openjdk-11-jre ykcs11

COPY ./target/eseal-1.0.0.jar ./eseal.jar
CMD ["bash" ,"start.sh"]